### ISSUE TITLE
Submit button on prediction page not working

### ISSUE THREAD

**Issue by octoma** [crypto-code/Stock-Market-AI-GUI#1]
As the title says. The submit form button isn't working

**Comment by crypto-code** [comment]
Does the loading icon show? Or is the button completely unresponsive? If the loading icon does show could you share the console output so I can see what the error is. I have tried out the project after cloning the same from git and it appears to work on my system. 

Have you run this before starting the server.
`python manage.py migrate`
Also ensure that javascript is enabled on your browser, since the submit button uses JS to do the submission to Django backend.

 I will look into it if this still doesn't work, but I will need more information to reproduce the error.

**Comment by octoma** [comment]
It was the (No of Future Days) option. I had selected an amount lower than 30days. I was able to edit the predict file and lower the minimum days.
